var PLAYER_SHUNT_DURATION   = 500;
var PLAYER_SHUNT_VELOCITY   = 250;
var PLAYER_MAX_VELOCITY     = 500;
var PLAYER_ACCELERATION     = 300;
var PLAYER_ANGULAR_VELOCITY = 250;
var PLAYER_BRAKE_DRAG       = 350;

var PLAYER_SHUNT_COOLDOWN = 1000;
var PLAYER_FIRE_COOLDOWN  = 100;

var PLAYER_SHIELD_RESPAWN_DELAY = 5000;


var ENEMY_MAX_VELOCITY = 350;
var ENEMY_FIRE_COOLDOWN = 750;


var SPAWN_INITIAL_DELAY = 4500;
var SPAWN_DELAY         = 2500;
var SPAWN_VARIANCE      = 1000;

var BULLET_SPEED = 500;
